**Aim:** To perform K-Fold cross-validation.

Write a program to Split the given dataset into K-train and test sets using K-Fold cross-validation.

In [2]:
from sklearn.datasets import make_classification
import pandas as pd

X,y=make_classification(n_samples=10,n_features=4,n_classes=2)
import numpy as np
def kfold_indices(data, k):
    fold_size = len(data) // k
    indices = np.arange(len(data))
    folds = []
    for i in range(k):
        test_indices = indices[i * fold_size: (i + 1) * fold_size]
        train_indices = np.concatenate([indices[:i * fold_size], indices[(i + 1) * fold_size:]])
        folds.append((train_indices, test_indices))
    return folds

# Define the number of folds (K)
k = 5

# Get the fold indices
fold_indices = kfold_indices(X, k)

from sklearn.metrics import accuracy_score
from sklearn.tree import DecisionTreeClassifier  # import ML  model

# Initialize the machine learning model
model = DecisionTreeClassifier()

# Initialize a list to store the evaluation scores
scores = []

# Iterate through each fold
for train_indices, test_indices in fold_indices:
    X_train, y_train = X[train_indices], y[train_indices]
    X_test, y_test = X[test_indices], y[test_indices]

    print('X_train samples')
    print(X_train)
    print('X_test samples')
    print(X_test)
    # Train the model on the training data
    model.fit(X_train, y_train)

    # Make predictions on the test data
    y_pred = model.predict(X_test)

    # Calculate the accuracy score for this fold
    fold_score = accuracy_score(y_test, y_pred)

    # Append the fold score to the list of scores
    scores.append(fold_score)

# Calculate the mean accuracy across all folds
mean_accuracy = np.mean(scores)
print("K-Fold Cross-Validation Scores:", scores)
print("Mean Accuracy:", mean_accuracy)


X_train samples
[[-0.79281634 -0.5820131  -0.11331237 -0.10871911]
 [-1.46489221 -1.60120084  0.12895752 -0.1105267 ]
 [-0.63275567  1.13361552 -1.11872722 -0.36138881]
 [ 1.45434817  0.65795614  0.47147203  0.26983595]
 [-1.06031621 -0.38944316 -0.40180471 -0.21223675]
 [ 1.38618884  2.1423665  -0.52558691 -0.00318697]
 [ 0.25505959 -1.61123615  1.19365823  0.34402313]
 [-0.34239515  0.94737898 -0.82024442 -0.25294078]]
X_test samples
[[-2.05382896 -0.65984508 -0.83910226 -0.42734143]
 [ 0.82834265 -1.01996733  1.16594176  0.39335347]]
X_train samples
[[-2.05382896 -0.65984508 -0.83910226 -0.42734143]
 [ 0.82834265 -1.01996733  1.16594176  0.39335347]
 [-0.63275567  1.13361552 -1.11872722 -0.36138881]
 [ 1.45434817  0.65795614  0.47147203  0.26983595]
 [-1.06031621 -0.38944316 -0.40180471 -0.21223675]
 [ 1.38618884  2.1423665  -0.52558691 -0.00318697]
 [ 0.25505959 -1.61123615  1.19365823  0.34402313]
 [-0.34239515  0.94737898 -0.82024442 -0.25294078]]
X_test samples
[[-0.79281634 -0.